debian/: Update, and simplify, init script
- Create /var/cache/inadyn and /run/inadyn dirs
- Simplify daemon args, rely on daemon built-in defaults
- Remove --test phase for start-stop-daemon, daemon check exists

Signed-off-by: Joachim Nilsson <troglobit@gmail.com>

diff --git a/debian/inadyn.init b/debian/inadyn.init
--- a/debian/inadyn.init
+++ b/debian/inadyn.init
@@ -14,15 +14,14 @@
 PATH=/sbin:/usr/sbin:/bin:/usr/bin
 DESC="DynDNS client"
 NAME=inadyn
-DAEMON=/usr/bin/inadyn
-CACHEDIR=/run/$NAME
-PIDFILE=$CACHEDIR/$NAME.pid
+DAEMON=/usr/sbin/$NAME
+RUNDIR=/run/$NAME
+CACHEDIR=/var/cache/$NAME
+PIDFILE=/$RUNDIR/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
 DEFAULT=/etc/default/$NAME
-CONFIG=/etc/$NAME.conf
 
 [ -x $DAEMON ] || exit 0
-
 [ -r $DEFAULT ] && . $DEFAULT
 
 . /lib/lsb/init-functions
@@ -38,87 +37,90 @@ if [ "$RUN_DAEMON" != "yes" ] && [ "$1" != "stop" ]; then
 fi
 
 DAEMON_ARGS="--pidfile $PIDFILE \
-             --config $CONFIG \
              --background \
              --drop-privs $USER:$GROUP"
 
-create_cache_dir() {
-    # Create the cache empty dir if necessary
-    if [ ! -d $CACHEDIR ]; then
-        mkdir $CACHEDIR
-        chmod 0755 $CACHEDIR
-	chown $USER:$GROUP $CACHEDIR
-    fi
+# Create essential dirs and chown, if missing
+create_dirs() {
+    for dir in $RUNDIR $CACHEDIR; do
+	if [ ! -d $dir ]; then
+            mkdir $dir
+            chmod 0755 $dir
+	    chown $USER:$GROUP $dir
+	fi
+    done
 }
 
 do_start()
 {
-	create_cache_dir
-	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
-		|| return 1
-	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
-		$DAEMON_ARGS \
-		|| return 2
+	create_dirs
+	start-stop-daemon --start --quiet --test \
+			  --pidfile $PIDFILE --exec $DAEMON > /dev/null \
+	    || return 1
+	start-stop-daemon --start --quiet        \
+			  --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_ARGS \
+	    || return 2
 }
 
 do_stop()
 {
-	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
-	RETVAL="$?"
-	[ "$RETVAL" = 2 ] && return 2
-	rm -f $PIDFILE
-	return "$RETVAL"
+    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 \
+		      --pidfile $PIDFILE --name $NAME
+    RETVAL="$?"
+    [ "$RETVAL" = 2 ] && return 2
+    rm -f $PIDFILE
+    return "$RETVAL"
 }
 
 do_reload() {
-	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
-	return 0
+    start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
+    return 0
 }
 
 case "$1" in
-  start)
-    log_daemon_msg "Starting $DESC " "$NAME"
-    do_start
-    case "$?" in
-		0|1) log_end_msg 0 ;;
-		2) log_end_msg 1 ;;
+    start)
+	log_daemon_msg "Starting $DESC " "$NAME"
+	do_start
+	case "$?" in
+	    0|1) log_end_msg 0 ;;
+	    2) log_end_msg 1 ;;
 	esac
-  ;;
-  stop)
+	;;
+    stop)
 	log_daemon_msg "Stopping $DESC" "$NAME"
 	do_stop
 	case "$?" in
-		0|1) log_end_msg 0 ;;
-		2) log_end_msg 1 ;;
+	    0|1) log_end_msg 0 ;;
+	    2) log_end_msg 1 ;;
 	esac
 	;;
-  status)
-       status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
-       ;;
-  reload|force-reload)
+    status)
+	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+	;;
+    reload|force-reload)
 	log_daemon_msg "Reloading $DESC" "$NAME"
 	do_reload
 	log_end_msg $?
 	;;
-  restart)
+    restart)
 	log_daemon_msg "Restarting $DESC" "$NAME"
 	do_stop
 	case "$?" in
-	  0|1)
+	    0|1)
 		do_start
 		case "$?" in
-			0) log_end_msg 0 ;;
-			1) log_end_msg 1 ;; # Old process is still running
-			*) log_end_msg 1 ;; # Failed to start
+		    0) log_end_msg 0 ;;
+		    1) log_end_msg 1 ;; # Old process is still running
+		    *) log_end_msg 1 ;; # Failed to start
 		esac
 		;;
-	  *)
+	    *)
 	  	# Failed to stop
 		log_end_msg 1
 		;;
 	esac
 	;;
-  *)
+    *)
 	echo "Usage: $SCRIPTNAME {start|stop|status|restart|reload|force-reload}" >&2
 	exit 3
 	;;
